version: 2.1
jobs:
  Infra:
    ddocker:
      image: weaveworks/eksctl  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            echo make awsinstall

      - run:
          name: Build Infra
          command: |
            echo make infra
            eksctl create cluster --name nginxhellosimple --regikubectl create namespace nginxhellosimpleon us-west-2 --nodegroup-name nginx-nodes --node-type t2.small --nodes 3 --nodes-min 1 --ssh-access --ssh-public-key udacity --managed
      - persist_to_workspace:
          root: ~/.kube
          paths:
            - config
    
  Lint:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make lintinstall

      - run:
          name: run lint
          command: |
            make lint 

  Build_and_Upload:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: build image
          command: |
            make build 

      - run:
          name: upload image
          command: |
            make login tag upload 

  Deploy_and_Run:
    docker: 
      image: bitnami/kubectl
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      - attach_workspace:
          at: ~/.kube
      - run:
          name: Config kubectl
          command: |
            aws eks --region us-west-2  update-kubeconfig --name nginxhellosimple
      - run:
          name: rolling update
          command: |
            make deploy

workflows:
  version: 2
  lint-build-and-deploy:
    jobs:
      - Infra
      - Lint
      - Build_and_Upload:
          requires:
            - Lint
      - Deploy_and_Run:
          requires:
            - Build_and_Upload