version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "DockerfilePlainText" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            make install
      - save_cache:
          paths:
          - ./
          key: v1-dependencies-{{ checksum "DockerfilePlainText" }}

        # run lint!
      - run:
          name: run lint
          command: |
            make lint 

      - run:
          name: build image
          command: |
            make build 
