version: 2.1
jobs:
  EKSCluster:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make awstools   
      - run:
          name: Build EKS Cluster
          command: |
            make cluster 

  Lint:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make lintinstall

      - run:
          name: run lint
          command: |
            make lint 

  Build_and_Upload:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: build image
          command: |
            make build 

      - run:
          name: upload image
          command: |
            make login tag upload 
  Namespace:
    docker: 
      - image: amazon/aws-cli
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      - run:
          name: install dependencies
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl &&\
              chmod +x ./kubectl   
      - run:
          name: Config kubectl
          command: |
            aws eks --region us-west-2  update-kubeconfig --name nginxhellosimple
      - run:
          name: Create Namespace
          command: |
            ./kubectl create namespace nginxhellosimple 

  Deploy_and_Run:
    docker: 
      - image: amazon/aws-cli
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
     - run:
          name: install dependencies
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl &&\
              chmod +x ./kubectl
      - run:
          name: Config kubectl
          command: |
            aws eks --region us-west-2  update-kubeconfig --name nginxhellosimple
      - run:
          name: rolling update
          command: |
            ./kubectl apply -f nginxhello_service.yml
            ./kubectl set image deployment nginxhellosimple=242437545548.dkr.ecr.us-west-2.amazonaws.com/nginxhellosimple:latest --all

workflows:
  version: 2
  lint-build-and-deploy:
    jobs:
      - Namespace
      - Lint
      - Build_and_Upload:
          requires:
            - Lint
      - Deploy_and_Run:
          requires:
            - Build_and_Upload