version: 2.1
jobs:
  Lint:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make lintinstall

      - run:
          name: run lint
          command: |
            make lint 

  Build_and_Upload:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: build image
          command: |
            make build 

      - run:
          name: upload image
          command: |
            make login tag upload 

  Deploy_and_Run:
    machine: true
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      - run:
          name: Config kubectl
          command: |
            make awsinstall config
      - run:
          name: rolling update
          command: |
            make delpoy

workflows:
  version: 2
  lint-build-and-deploy:
    jobs:
      - Lint
      - Build_and_Upload:
          requires:
            - Lint
      - Deploy_and_Run:
          requires:
            - Build_and_Upload