version: 2.1
jobs:
  EKSCluster:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make awstools   
      - run:
          name: Build EKS Cluster
          command: |
            make cluster 

  Lint:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: install dependencies
          command: |
            make lintinstall

      - run:
          name: run lint
          command: |
            make lint 

  Build_and_Upload:
    machine: true  
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos

      - run:
          name: build image
          command: |
            make build 

      - run:
          name: upload image
          command: |
            make login tag upload 
  Namespace:
    docker: 
      - image: amazon/aws-cli
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      - run:
          name: install dependencies
          command: |
            make awstools   
      - run:
          name: Create Namespace
          command: |
            make namespace 

  Deploy_and_Run:
    docker: 
      - image: amazon/aws-cli
    working_directory: ~/NGINX-Demos/nginx-hello

    steps:
      - checkout:
          path: ~/NGINX-Demos
      - run:
          name: Config kubectl
          command: |
            make config
      - run:
          name: rolling update
          command: |
            make deploy

workflows:
  version: 2
  lint-build-and-deploy:
    jobs:
      - Infra
      - Lint
      - Build_and_Upload:
          requires:
            - Lint
      - Deploy_and_Run:
          requires:
            - Build_and_Upload