apiVersion: v1
kind: Service
metadata:
  name: nginxhellosimple
  namespace: nginxhellosimple
  labels:
    app: nginxhellosimple
spec:
  selector:
    app: nginxhellosimple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhellosimple
  namespace: nginxhellosimple
  labels:
    app: nginxhellosimple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxhellosimple
  template:
    metadata:
      labels:
        app: nginxhellosimple
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginxhellosimple
        image: 242437545548.dkr.ecr.us-west-2.amazonaws.com/nginxhellosimple
        ports:
        - containerPort: 80